codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 0.5%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  require_changes: no
