#!/usr/bin/env Rscript
# ============================================================================
# TSENAT Plotting Functions - Toy Data Example
# ============================================================================
# This script uses ACTUAL TSENAT plotting functions from vignette
# Uses real TSENAT functions: calculate_diversity(), calculate_lm_interaction(), etc.
# ============================================================================

devtools::load_all()
library(SummarizedExperiment)
library(ggplot2)

set.seed(42)

# Setup for loading intermediate files from inst/extdata
extdata_dir <- system.file("extdata", package = "TSENAT")

message("\n" %+% strrep("=", 78))
message("TSENAT PLOTTING - VIGNETTE PLOT FUNCTIONS")
message(strrep("=", 78) %+% "\n")

# ============================================================================
# LOAD REAL DATA FROM TSENAT PACKAGE
# ============================================================================

message("Loading real TSENAT dataset...\n")

# Load the built-in TSENAT readcounts data
data(readcounts)
readcounts <- as.matrix(salmon_dataset)
mode(readcounts) <- "numeric"

message(sprintf("Full dataset: %d transcripts × %d samples\n", nrow(readcounts), ncol(readcounts)))

# Use a LARGER gene subset (300-400 genes) to have more data after filtering
# This gives GAM better statistical power to fit curves
set.seed(42)
tx2gene <- read.table(
  system.file("extdata", "tx2gene.tsv", package = "TSENAT"),
  header = TRUE, sep = "\t"
)

# tx2gene has columns: transcript_id, gene_name
# Sample 300 unique genes to ensure enough remain after filtering for GAM
unique_genes <- unique(tx2gene$gene_name)
n_genes_subset <- min(300, length(unique_genes))
selected_genes <- unique_genes[sample.int(length(unique_genes), n_genes_subset)]

# Get transcripts for selected genes and KEEP ALL 16 SAMPLES
subset_tx_match <- tx2gene$gene_name %in% selected_genes
subset_tx <- tx2gene$transcript_id[subset_tx_match]

# Subset the expression matrix using transcript IDs (transcripts only, all samples)
expr_matrix <- readcounts[subset_tx, ]

message(sprintf("Working with: %d transcripts × %d samples (%d genes)\n", 
                nrow(expr_matrix), ncol(expr_matrix), n_genes_subset))

# Load metadata (use ALL samples, will be matched to all 16 samples in expr_matrix)
metadata_df <- read.table(
  system.file("extdata", "metadata.tsv", package = "TSENAT"),
  header = TRUE, sep = "\t"
)

# Get the GFF3 annotation for build_se
gff3_file <- system.file("extdata", "annotation.gff3.gz", package = "TSENAT")

message(sprintf("Using all %d samples from metadata for better GAM fitting\n", nrow(metadata_df)))

# ============================================================================
# BUILD TRANSCRIPT-LEVEL SE USING TSENAT build_se
# ============================================================================

message("Building transcript-level SummarizedExperiment...\n")

se <- build_se(expr_matrix, gff3_file, metadata = metadata_df)

message(sprintf("SE built: %d transcripts × %d samples\n", nrow(se), ncol(se)))

# ============================================================================
# FILTER LOW-ABUNDANCE TRANSCRIPTS
# ============================================================================

message("Loading filtered transcripts from inst/extdata...\\n")

# Load filtered SE from inst/extdata (generated by TSENAT.Rmd vignette)
filtered_se_file <- file.path(extdata_dir, "se_filtered_medium.rds")

if (file.exists(filtered_se_file)) {
    se <- readRDS(filtered_se_file)
    message(sprintf("Loaded filtered SummarizedExperiment\n"))
} else {
    stop(sprintf("ERROR: Filtered SE not found at %s\n", filtered_se_file))
}

message(sprintf("Loaded: %d transcripts × %d samples\\n", nrow(se), ncol(se)))

# ============================================================================
# LOAD DIVERSITY RESULTS
# ============================================================================

message("Loading Tsallis entropy results from inst/extdata...\\n")

# Use 4 q-values (must match vignette q_spectrum)
q_spectrum <- c(0.5, 1, 1.5, 2)

# Load diversity results from inst/extdata (generated by TSENAT.Rmd vignette)
diversity_file <- file.path(extdata_dir, "ts_se_diversity.rds")

if (file.exists(diversity_file)) {
    ts_se <- readRDS(diversity_file)
    message(sprintf("Loaded diversity results\\n"))
} else {
    stop(sprintf("ERROR: Diversity results not found at %s\\n", diversity_file))
}

message(sprintf("Loaded: %d genes × %d q-values\\n", nrow(ts_se), ncol(ts_se)))

# ============================================================================
# OUTPUT DIRECTORY
# ============================================================================

output_dir <- "output"
if (!dir.exists(output_dir)) {
  dir.create(output_dir)
}

message(strrep("=", 78))
message("VIGNETTE PLOT FUNCTIONS")
message(strrep("=", 78) %+% "\n")

# ============================================================================
# Plot 1: plot_tsallis_q_curve
# ============================================================================

message("1) plot_tsallis_q_curve() - Q-curve across diversity scales\n")

tryCatch({
  p_qcurve <- plot_tsallis_q_curve(ts_se)
  png(file.path(output_dir, "01_plot_tsallis_q_curve.png"), width = 1000, height = 600)
  print(p_qcurve)
  dev.off()
  message("   ✓ Saved: 01_plot_tsallis_q_curve.png\n")
}, error = function(e) {
  message(sprintf("   ✗ Error: %s\n", e$message))
})

# ============================================================================
# Plot 2: plot_lm_interaction_gam
# ============================================================================

message("2) plot_lm_interaction_gam() - Top genes by q×group interaction\n")

lm_res <- NULL
tryCatch({
  # Load LM interaction results from inst/extdata (generated by TSENAT.Rmd vignette)
  lm_res_file <- file.path(extdata_dir, "lm_res_interaction.rds")
  
  if (file.exists(lm_res_file)) {
    lm_res <- readRDS(lm_res_file)
    message("   Loaded LM interaction results\\n")
  } else {
    message(sprintf("   WARNING: LM interaction results not found at %s\\n", lm_res_file))
    message("   Skipping plots that depend on LM results\n")
    lm_res <- NULL
  }
  
  # Check what we got back
  if (is.null(lm_res)) {
    message("   ⚠ LM results not available\n")
  } else if (!is.list(lm_res)) {
    message(sprintf("   ⚠ Unexpected return type: %s\n", class(lm_res)))
  } else {
    message(sprintf("   Got lm_res with elements: %s\n", paste(names(lm_res), collapse=", ")))
    if (!is.null(lm_res$results)) {
      message(sprintf("   Found %d genes with results", nrow(lm_res$results)))
    }
  }
    
    if (!is.null(lm_res) && !is.null(lm_res$results) && nrow(lm_res$results) > 0) {
      # Sort by p-value to get top hits (use any genes, not just significant)
      lm_res$results <- lm_res$results[order(lm_res$results$p_interaction), ]
      
      message(sprintf("   Plotting interaction profiles for top genes...\n"))
      # Try with top genes regardless of significance
      combined_plot <- tryCatch({
        result <- plot_lm_interaction_gam(
          se = ts_se,
          lm_res = lm_res,
          n_top = 4
        )
        result
      }, error = function(e) {
        message(sprintf("   Plot error details:\n"))
        message(sprintf("     Message: %s\n", e$message))
        if (!is.null(e$call)) {
          message(sprintf("     Call: %s\n", deparse(e$call)))
        }
        NULL
      }, warning = function(w) {
        message(sprintf("   Plot warning: %s\n", w$message))
        NULL
      })
      
      if (!is.null(combined_plot)) {
        png(file.path(output_dir, "02_plot_lm_interaction_gam.png"), width = 1400, height = 1000)
        print(combined_plot)
        dev.off()
        message("   ✓ Saved: 02_plot_lm_interaction_gam.png\n")
      } else {
        message("   ⚠ Plot generation failed\n")
      }
    } else {
      message("   ⚠ No interaction results found\n")
    }
}, error = function(e) {
  message(sprintf("   ⚠ Skipped: %s\n", e$message))
})

# ============================================================================
# Plot 3: plot_multiq_delta_influence_heatmaps
# ============================================================================

message("3) plot_multiq_delta_influence_heatmaps() - Transcript switching\n")

tryCatch({
  if (!is.null(lm_res) && !is.null(lm_res$results)) {
    message("   Loading jackknife isoform switching results...")
    # Load switching results from inst/extdata
    switching_file <- file.path(extdata_dir, "multi_q_switching_results.rds")
    
    if (file.exists(switching_file)) {
      multi_q_results <- readRDS(switching_file)
      message(sprintf("   Loaded switching results\\n"))
    } else {
      message(sprintf("   WARNING: Switching results not found at %s\\n", switching_file))
      multi_q_results <- NULL
    }
    
    message(sprintf("   Got %s switching results object\\n", 
                   if(is.null(multi_q_results)) "NULL" else class(multi_q_results)[1]))
    
    if (!is.null(multi_q_results) && inherits(multi_q_results, "tsenat_isoform_switching_multiq")) {
      message(sprintf("   Generating heatmap for switching results...\\n"))
      tryCatch({
        heatmap_file_temp <- plot_multiq_delta_influence_heatmaps(
          switching_results = multi_q_results,
          n_genes = 4,
          lm_results = if(!is.null(lm_res)) lm_res$results else NULL
        )
        # Copy temp file to output directory with proper naming
        if (!is.null(heatmap_file_temp) && file.exists(heatmap_file_temp)) {
          heatmap_file_output <- file.path(output_dir, "03_plot_multiq_delta_influence_heatmaps.png")
          file.copy(heatmap_file_temp, heatmap_file_output, overwrite = TRUE)
          unlink(heatmap_file_temp)  # Clean up temp file
          message(sprintf("   ✓ Saved: 03_plot_multiq_delta_influence_heatmaps.png\n"))
        } else {
          message("   ⚠ Heatmap file not created\n")
        }
      }, error = function(e) {
        message(sprintf("   ⚠ Heatmap plot failed: %s\n", substr(e$message, 1, 60)))
      })
    } else {
      message("   ⚠ Switching results format incorrect or missing\n")
      message("   ⚠ Skipping heatmap generation\n")
    }
  } else {
    message("   ⚠ Missing prerequisites (lm_res)\n")
  }
}, error = function(e) {
  message(sprintf("   ⚠ Error: %s\n", e$message))
})

# ============================================================================
# Plot 4: plot_top_transcripts
# ============================================================================

message("4) plot_top_transcripts() - Top transcript abundance\n")

tryCatch({
  if (!is.null(lm_res) && !is.null(lm_res$results) && nrow(lm_res$results) > 0) {
    p <- tryCatch({
      plot_top_transcripts(
        se,
        res = lm_res,
        top_n = min(4, nrow(se)),
        metric = "median"
      )
    }, error = function(e) NULL)
    
    if (!is.null(p)) {
      png(file.path(output_dir, "04_plot_top_transcripts.png"), width = 1400, height = 1000)
      print(p)
      dev.off()
      message("   ✓ Saved: 04_plot_top_transcripts.png\n")
    } else {
      message("   ⚠ Plot generation failed\n")
    }
  } else {
    message("   ⚠ No interaction results for top transcripts\n")
  }
}, error = function(e) {
  message(sprintf("   ⚠ Error: %s\n", e$message))
})

# ============================================================================
# Plot 5: plot_divergence_distribution
# ============================================================================

message("5) plot_divergence_distribution() - Effect size distribution\n")

divergence_results_se <- NULL
tryCatch({
  # Load divergence results from inst/extdata (generated by TSENAT.Rmd vignette)
  divergence_file <- file.path(extdata_dir, "divergence_results_se.rds")
  
  if (file.exists(divergence_file)) {
    divergence_results_se <- readRDS(divergence_file)
    message("   Loaded divergence results\n")
  } else {
    message(sprintf("   WARNING: Divergence results not found at %s\n", divergence_file))
    divergence_results_se <- NULL
  }
  
  if (!is.null(divergence_results_se) && nrow(divergence_results_se) > 0) {
    # Build interaction_results with per-q effect sizes
    div_assay <- assay(divergence_results_se)
    gene_names <- rowData(divergence_results_se)$gene_name
    
    # Create data frame with effect_size columns for each q
    interaction_results <- data.frame(gene = gene_names)
    
    # Add effect size columns for each q value
    for (i in seq_along(q_spectrum)) {
      q_val <- q_spectrum[i]
      col_name <- paste0("effect_size_D_q", sub("\\.", "_", as.character(q_val)))
      col_idx <- min(i, ncol(div_assay))
      if (col_idx <= ncol(div_assay)) {
        interaction_results[[col_name]] <- div_assay[, col_idx, drop=TRUE]
      }
    }
    
    # Add p_value column (mock for visualization)
    interaction_results$p_value <- apply(div_assay, 1, function(x) mean(x, na.rm=TRUE) / (sd(x, na.rm=TRUE) + 1e-6))
    
    p <- tryCatch({
      plot_divergence_distribution(interaction_results, threshold = 0.5)
    }, error = function(e) {
      message(sprintf("   ⚠ Plot failed: %s\n", substr(e$message, 1, 50)))
      NULL
    })
    
    if (!is.null(p)) {
      png(file.path(output_dir, "05_plot_divergence_distribution.png"), width = 1000, height = 600)
      print(p)
      dev.off()
      message("   ✓ Saved: 05_plot_divergence_distribution.png\n")
    } else {
      message("   ⚠ Could not generate divergence plot\n")
    }
  } else {
    message("   ⚠ No divergence results available\n")
  }
}, error = function(e) {
  message(sprintf("   ⚠ Error: %s\n", substr(e$message, 1, 60)))
})

# ============================================================================
# Plot 6: plot_divergence_spectrum
# ============================================================================

message("6) plot_divergence_spectrum() - Q-spectrum heatmap\n")

tryCatch({
  if (!is.null(divergence_results_se) && nrow(divergence_results_se) > 0) {
    p <- plot_divergence_spectrum(divergence_results_se)
    png(file.path(output_dir, "06_plot_divergence_spectrum.png"), width = 1000, height = 600)
    print(p)
    dev.off()
    message("   ✓ Saved: 06_plot_divergence_spectrum.png\n")
  }
}, error = function(e) {
  message(sprintf("   ✗ Error: %s\n", e$message))
})

# ============================================================================
# Plot 7: plot_divergence_spectrum (multi-gene mode with lm_res ranking)
# ============================================================================

message("7) plot_divergence_spectrum() - Top genes divergence spectra\n")

tryCatch({
  if (!is.null(divergence_results_se) && !is.null(lm_res)) {
    
    message("   Plotting top genes ranked by interaction significance...\n")
    
    p_multi <- tryCatch({
      result <- plot_divergence_spectrum(
        divergence_results_se = divergence_results_se,
        lm_res = if(!is.null(lm_res)) lm_res$results else NULL,
        n_genes = 4,
        ncol = 2
      )
      message("   Plot created successfully\n")
      result
    }, error = function(e) {
      message(sprintf("   Error in plot_divergence_spectrum: %s\n", e$message))
      NULL
    })
    
    if (!is.null(p_multi)) {
      tryCatch({
        png(file.path(output_dir, "07_plot_divergence_spectrum_top_genes.png"), width = 1400, height = 800)
        print(p_multi)
        dev.off()
        message("   ✓ Saved: 07_plot_divergence_spectrum_top_genes.png\n")
      }, error = function(e) {
        message(sprintf("   ⚠ Error saving plot: %s\n", e$message))
        try(dev.off(), silent = TRUE)
      })
    } else {
      message("   ⚠ Plot generation returned NULL\n")
    }
  } else {
    message("   ⚠ Missing required inputs: divergence_results_se or lm_res\n")
  }
}, error = function(e) {
  message(sprintf("   ⚠ Error: %s\n", e$message))
})

# ============================================================================
# SUMMARY
# ============================================================================

message("\n" %+% strrep("=", 78))
message("SUMMARY - ALL VIGNETTE PLOTTING FUNCTIONS")
message(strrep("=", 78) %+% "\n")

cat("Functions from TSENAT.Rmd vignette used:

1. plot_tsallis_q_curve(ts_se)
   - Global q-curve with entropy across sensitivity parameter q
   - Shows group separation at different scales

2. plot_lm_interaction_gam(se, lm_res, n_top)
   - Q-curve profiles for top genes with q×group interactions
   - Uses GAM to fit flexible q-response curves

3. plot_multiq_delta_influence_heatmaps(switching_results, n_genes, lm_results)
   - Heatmaps of jackknife weights per transcript across q-spectrum
   - Visualizes transcript-level switching patterns

4. plot_top_transcripts(se, res, top_n, metric)
   - Heatmap of transcript abundance for top genes
   - Sorted by median or mean expression

5. plot_divergence_distribution(interaction_results, threshold)
   - Ranked barplot of divergence scores (effect sizes)
   - Marks significance threshold

6. plot_divergence_spectrum(divergence_results_se, gene=NULL, lm_res=NULL)
   - Global gene × q heatmap showing divergence patterns
   - Single gene mode: divergence spectrum for one gene
   - Top N genes mode: faceted spectra ranked by significance

7. plot_divergence_spectrum(divergence_results_se, lm_res, n_genes=6)
   - Multi-gene mode: top N genes by interaction p-value
   - Compares divergence q-curves across significant genes
")

message("\n" %+% strrep("=", 78))
message(sprintf("✓ Complete! Results saved to: %s/\n", output_dir))

# List generated files
generated_files <- list.files(output_dir, pattern = "0[1-7]_plot.*\\.png$")
if (length(generated_files) > 0) {
  cat("Generated plots:\n")
  for (f in sort(generated_files)) {
    file_path <- file.path(output_dir, f)
    size_kb <- file.size(file_path) / 1024
    cat(sprintf("  ✓ %s (%.1f KB)\n", f, size_kb))
  }
} else {
  cat("  (Some plots may not generate if convergence fails or data too small)\n")
}

cat("\n")
