source('R/diversity_functions.R')
source('R/calculate_method.R')
source('R/calculate_diversity.R')
source('R/calculate_difference.R')
if (file.exists('R/infer_sample_groups.R')) source('R/infer_sample_groups.R')
cat('Sourced files\n')
trace('calculate_lm_interaction', tracer = quote(cat('TRACE: entered calculate_lm_interaction\n')) , print = FALSE)
# Create small SE
library(SummarizedExperiment)
mat <- matrix(runif(6,0.2,1.5), nrow=2)
rownames(mat) <- c('Gene1','Gene2')
colnames(mat) <- c('A_q=0.5','A_q=1','A_q=2','B_q=0.5','B_q=1','B_q=2')
coldata <- SummarizedExperiment::DataFrame(samples=colnames(mat), group=rep(c('Normal','Tumor'), each=3), row.names = colnames(mat))
se_small <- SummarizedExperiment::SummarizedExperiment(assays = list(diversity = mat), colData = coldata)
cat('About to call calculate_lm_interaction\n')
res <- calculate_lm_interaction(se_small, sample_type_col = 'group', method = 'fpca', min_obs = 2)
cat('Returned from calculate_lm_interaction\n')
print(res)
