// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// entropy_cpp
double entropy_cpp(NumericVector p, double q, bool normalize, double log_base);
RcppExport SEXP _TSENAT_entropy_cpp(SEXP pSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(entropy_cpp(p, q, normalize, log_base));
    return rcpp_result_gen;
END_RCPP
}
// jackknife_resampling_cpp
List jackknife_resampling_cpp(NumericMatrix counts, double q, bool normalize, double log_base, double pseudocount);
RcppExport SEXP _TSENAT_jackknife_resampling_cpp(SEXP countsSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    rcpp_result_gen = Rcpp::wrap(jackknife_resampling_cpp(counts, q, normalize, log_base, pseudocount));
    return rcpp_result_gen;
END_RCPP
}
// check_rcpp_available
bool check_rcpp_available();
RcppExport SEXP _TSENAT_check_rcpp_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(check_rcpp_available());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TSENAT_entropy_cpp", (DL_FUNC) &_TSENAT_entropy_cpp, 4},
    {"_TSENAT_jackknife_resampling_cpp", (DL_FUNC) &_TSENAT_jackknife_resampling_cpp, 5},
    {"_TSENAT_check_rcpp_available", (DL_FUNC) &_TSENAT_check_rcpp_available, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_TSENAT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
