// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// entropy_cpp
double entropy_cpp(NumericVector p, double q, bool normalize, double log_base);
RcppExport SEXP _TSENAT_entropy_cpp(SEXP pSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(entropy_cpp(p, q, normalize, log_base));
    return rcpp_result_gen;
END_RCPP
}
// jackknife_resampling_cpp
List jackknife_resampling_cpp(NumericMatrix counts, double q, bool normalize, double log_base, double pseudocount);
RcppExport SEXP _TSENAT_jackknife_resampling_cpp(SEXP countsSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    rcpp_result_gen = Rcpp::wrap(jackknife_resampling_cpp(counts, q, normalize, log_base, pseudocount));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_compute_cpp
NumericVector bootstrap_compute_cpp(NumericVector x, int nboot, double q, bool normalize, double log_base, double pseudocount);
RcppExport SEXP _TSENAT_bootstrap_compute_cpp(SEXP xSEXP, SEXP nbootSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_compute_cpp(x, nboot, q, normalize, log_base, pseudocount));
    return rcpp_result_gen;
END_RCPP
}
// block_bootstrap_compute_cpp
NumericVector block_bootstrap_compute_cpp(NumericVector x, int nboot, double q, bool normalize, double log_base, double pseudocount);
RcppExport SEXP _TSENAT_block_bootstrap_compute_cpp(SEXP xSEXP, SEXP nbootSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    rcpp_result_gen = Rcpp::wrap(block_bootstrap_compute_cpp(x, nboot, q, normalize, log_base, pseudocount));
    return rcpp_result_gen;
END_RCPP
}
// jis_tsallis_entropy_cpp
NumericVector jis_tsallis_entropy_cpp(NumericMatrix counts, double q, bool normalize, double log_base, double pseudocount, int n_tx_fixed);
RcppExport SEXP _TSENAT_jis_tsallis_entropy_cpp(SEXP countsSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP, SEXP n_tx_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< int >::type n_tx_fixed(n_tx_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(jis_tsallis_entropy_cpp(counts, q, normalize, log_base, pseudocount, n_tx_fixed));
    return rcpp_result_gen;
END_RCPP
}
// jis_jackknife_influences_cpp
NumericVector jis_jackknife_influences_cpp(NumericMatrix counts, double q, bool normalize, double log_base, double pseudocount, int n_tx_fixed);
RcppExport SEXP _TSENAT_jis_jackknife_influences_cpp(SEXP countsSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP, SEXP n_tx_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< int >::type n_tx_fixed(n_tx_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(jis_jackknife_influences_cpp(counts, q, normalize, log_base, pseudocount, n_tx_fixed));
    return rcpp_result_gen;
END_RCPP
}
// jis_bootstrap_delta_cpp
List jis_bootstrap_delta_cpp(NumericMatrix counts_A, NumericMatrix counts_B, NumericVector delta_influence, double q, bool normalize, double log_base, double pseudocount, int nboot, double confidence, String method, int n_transcripts_fixed);
RcppExport SEXP _TSENAT_jis_bootstrap_delta_cpp(SEXP counts_ASEXP, SEXP counts_BSEXP, SEXP delta_influenceSEXP, SEXP qSEXP, SEXP normalizeSEXP, SEXP log_baseSEXP, SEXP pseudocountSEXP, SEXP nbootSEXP, SEXP confidenceSEXP, SEXP methodSEXP, SEXP n_transcripts_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts_A(counts_ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type counts_B(counts_BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta_influence(delta_influenceSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< double >::type confidence(confidenceSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type n_transcripts_fixed(n_transcripts_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(jis_bootstrap_delta_cpp(counts_A, counts_B, delta_influence, q, normalize, log_base, pseudocount, nboot, confidence, method, n_transcripts_fixed));
    return rcpp_result_gen;
END_RCPP
}
// tsallis_divergence_cpp
double tsallis_divergence_cpp(NumericVector p, NumericVector r, double q, double log_base);
RcppExport SEXP _TSENAT_tsallis_divergence_cpp(SEXP pSEXP, SEXP rSEXP, SEXP qSEXP, SEXP log_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(tsallis_divergence_cpp(p, r, q, log_base));
    return rcpp_result_gen;
END_RCPP
}
// divergence_bootstrap_compute_cpp
NumericVector divergence_bootstrap_compute_cpp(NumericVector x, NumericVector y, int nboot, double q, bool paired, double pseudocount, double log_base);
RcppExport SEXP _TSENAT_divergence_bootstrap_compute_cpp(SEXP xSEXP, SEXP ySEXP, SEXP nbootSEXP, SEXP qSEXP, SEXP pairedSEXP, SEXP pseudocountSEXP, SEXP log_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type paired(pairedSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(divergence_bootstrap_compute_cpp(x, y, nboot, q, paired, pseudocount, log_base));
    return rcpp_result_gen;
END_RCPP
}
// divergence_bootstrap_paired_cpp
NumericVector divergence_bootstrap_paired_cpp(NumericVector x, NumericVector y, IntegerVector pair_ids, int nboot, double q, double pseudocount, double log_base);
RcppExport SEXP _TSENAT_divergence_bootstrap_paired_cpp(SEXP xSEXP, SEXP ySEXP, SEXP pair_idsSEXP, SEXP nbootSEXP, SEXP qSEXP, SEXP pseudocountSEXP, SEXP log_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_ids(pair_idsSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(divergence_bootstrap_paired_cpp(x, y, pair_ids, nboot, q, pseudocount, log_base));
    return rcpp_result_gen;
END_RCPP
}
// divergence_bootstrap_flexible_cpp
NumericVector divergence_bootstrap_flexible_cpp(NumericVector x, NumericVector y, IntegerVector x_pair_ids, IntegerVector y_pair_ids, int nboot, double q, double pseudocount, double log_base);
RcppExport SEXP _TSENAT_divergence_bootstrap_flexible_cpp(SEXP xSEXP, SEXP ySEXP, SEXP x_pair_idsSEXP, SEXP y_pair_idsSEXP, SEXP nbootSEXP, SEXP qSEXP, SEXP pseudocountSEXP, SEXP log_baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x_pair_ids(x_pair_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y_pair_ids(y_pair_idsSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    rcpp_result_gen = Rcpp::wrap(divergence_bootstrap_flexible_cpp(x, y, x_pair_ids, y_pair_ids, nboot, q, pseudocount, log_base));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TSENAT_entropy_cpp", (DL_FUNC) &_TSENAT_entropy_cpp, 4},
    {"_TSENAT_jackknife_resampling_cpp", (DL_FUNC) &_TSENAT_jackknife_resampling_cpp, 5},
    {"_TSENAT_bootstrap_compute_cpp", (DL_FUNC) &_TSENAT_bootstrap_compute_cpp, 6},
    {"_TSENAT_block_bootstrap_compute_cpp", (DL_FUNC) &_TSENAT_block_bootstrap_compute_cpp, 6},
    {"_TSENAT_jis_tsallis_entropy_cpp", (DL_FUNC) &_TSENAT_jis_tsallis_entropy_cpp, 6},
    {"_TSENAT_jis_jackknife_influences_cpp", (DL_FUNC) &_TSENAT_jis_jackknife_influences_cpp, 6},
    {"_TSENAT_jis_bootstrap_delta_cpp", (DL_FUNC) &_TSENAT_jis_bootstrap_delta_cpp, 11},
    {"_TSENAT_tsallis_divergence_cpp", (DL_FUNC) &_TSENAT_tsallis_divergence_cpp, 4},
    {"_TSENAT_divergence_bootstrap_compute_cpp", (DL_FUNC) &_TSENAT_divergence_bootstrap_compute_cpp, 7},
    {"_TSENAT_divergence_bootstrap_paired_cpp", (DL_FUNC) &_TSENAT_divergence_bootstrap_paired_cpp, 7},
    {"_TSENAT_divergence_bootstrap_flexible_cpp", (DL_FUNC) &_TSENAT_divergence_bootstrap_flexible_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_TSENAT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
