# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropy_cpp <- function(p, q = 1.0, normalize = TRUE, log_base = 2.718281828) {
    .Call(`_TSENAT_entropy_cpp`, p, q, normalize, log_base)
}

hill_number_cpp <- function(p, q = 1.0, log_base = 2.718281828) {
    .Call(`_TSENAT_hill_number_cpp`, p, q, log_base)
}

jackknife_resampling_cpp <- function(counts, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 0.0) {
    .Call(`_TSENAT_jackknife_resampling_cpp`, counts, q, normalize, log_base, pseudocount)
}

bootstrap_compute_cpp <- function(x, nboot = 1000L, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 0.0) {
    .Call(`_TSENAT_bootstrap_compute_cpp`, x, nboot, q, normalize, log_base, pseudocount)
}

bootstrap_entropy_vec_cpp <- function(boot_samples, q = 1.0, normalize = TRUE, log_base = 2.718281828) {
    .Call(`_TSENAT_bootstrap_entropy_vec_cpp`, boot_samples, q, normalize, log_base)
}

block_bootstrap_compute_cpp <- function(x, nboot = 1000L, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 0.0) {
    .Call(`_TSENAT_block_bootstrap_compute_cpp`, x, nboot, q, normalize, log_base, pseudocount)
}

#' @keywords internal
check_rcpp_available <- function() {
    .Call(`_TSENAT_check_rcpp_available`)
}

jis_tsallis_entropy_cpp <- function(counts, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 1e-8, n_tx_fixed = -1L) {
    .Call(`_TSENAT_jis_tsallis_entropy_cpp`, counts, q, normalize, log_base, pseudocount, n_tx_fixed)
}

jis_jackknife_influences_cpp <- function(counts, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 1e-8, n_tx_fixed = -1L) {
    .Call(`_TSENAT_jis_jackknife_influences_cpp`, counts, q, normalize, log_base, pseudocount, n_tx_fixed)
}

jis_bootstrap_delta_cpp <- function(counts_A, counts_B, delta_influence, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 1e-8, n_bootstrap = 1000L, confidence = 0.95, method = "percentile", n_transcripts_fixed = -1L) {
    .Call(`_TSENAT_jis_bootstrap_delta_cpp`, counts_A, counts_B, delta_influence, q, normalize, log_base, pseudocount, n_bootstrap, confidence, method, n_transcripts_fixed)
}

