# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropy_cpp <- function(p, q = 1.0, normalize = TRUE, log_base = 2.718281828) {
    .Call(`_TSENAT_entropy_cpp`, p, q, normalize, log_base)
}

jackknife_resampling_cpp <- function(counts, q = 1.0, normalize = TRUE, log_base = 2.718281828, pseudocount = 0.0) {
    .Call(`_TSENAT_jackknife_resampling_cpp`, counts, q, normalize, log_base, pseudocount)
}

#' @keywords internal
check_rcpp_available <- function() {
    .Call(`_TSENAT_check_rcpp_available`)
}

