# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator
# token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropy_cpp <- function(p, q = 1, normalize = TRUE, log_base = 2.718281828) {
    .Call(`_TSENAT_entropy_cpp`, p, q, normalize, log_base)
}

jackknife_resampling_cpp <- function(counts, q = 1, normalize = TRUE, log_base = 2.718281828,
    pseudocount = 0) {
    .Call(`_TSENAT_jackknife_resampling_cpp`, counts, q, normalize, log_base, pseudocount)
}

bootstrap_compute_cpp <- function(x, nboot = 1000L, q = 1, normalize = TRUE, log_base = 2.718281828,
    pseudocount = 0) {
    .Call(`_TSENAT_bootstrap_compute_cpp`, x, nboot, q, normalize, log_base, pseudocount)
}

block_bootstrap_compute_cpp <- function(x, nboot = 1000L, q = 1, normalize = TRUE,
    log_base = 2.718281828, pseudocount = 0) {
    .Call(`_TSENAT_block_bootstrap_compute_cpp`, x, nboot, q, normalize, log_base,
        pseudocount)
}

jis_tsallis_entropy_cpp <- function(counts, q = 1, normalize = TRUE, log_base = 2.718281828,
    pseudocount = 0, n_tx_fixed = -1L) {
    .Call(`_TSENAT_jis_tsallis_entropy_cpp`, counts, q, normalize, log_base, pseudocount,
        n_tx_fixed)
}

jis_jackknife_influences_cpp <- function(counts, q = 1, normalize = TRUE, log_base = 2.718281828,
    pseudocount = 0, n_tx_fixed = -1L) {
    .Call(`_TSENAT_jis_jackknife_influences_cpp`, counts, q, normalize, log_base,
        pseudocount, n_tx_fixed)
}

jis_bootstrap_delta_cpp <- function(counts_A, counts_B, delta_influence, q = 1, normalize = TRUE,
    log_base = 2.718281828, pseudocount = 1e-08, nboot = 1000L, confidence = 0.95,
    method = "percentile", n_transcripts_fixed = -1L) {
    .Call(`_TSENAT_jis_bootstrap_delta_cpp`, counts_A, counts_B, delta_influence,
        q, normalize, log_base, pseudocount, nboot, confidence, method, n_transcripts_fixed)
}

tsallis_divergence_cpp <- function(p, r, q = 1, log_base = 2.718281828) {
    .Call(`_TSENAT_tsallis_divergence_cpp`, p, r, q, log_base)
}

divergence_bootstrap_compute_cpp <- function(x, y, nboot = 1000L, q = 1, paired = FALSE,
    pseudocount = 0, log_base = 2.718281828) {
    .Call(`_TSENAT_divergence_bootstrap_compute_cpp`, x, y, nboot, q, paired, pseudocount,
        log_base)
}

divergence_bootstrap_paired_cpp <- function(x, y, pair_ids, nboot = 1000L, q = 1,
    pseudocount = 0, log_base = 2.718281828) {
    .Call(`_TSENAT_divergence_bootstrap_paired_cpp`, x, y, pair_ids, nboot, q, pseudocount,
        log_base)
}

divergence_bootstrap_flexible_cpp <- function(x, y, x_pair_ids, y_pair_ids, nboot = 1000L,
    q = 1, pseudocount = 0, log_base = 2.718281828) {
    .Call(`_TSENAT_divergence_bootstrap_flexible_cpp`, x, y, x_pair_ids, y_pair_ids,
        nboot, q, pseudocount, log_base)
}

